/**
 * @file Defines the TypeScript types for note and chat message chunks.
 */

/**
 * Input type for chunking note content.
 */
export interface NoteInputForChunking {

  /** The unique identifier of the original note. */
  id: string;

  /** The main textual content of the note. */
  content: string;

  /** The title of the note, if available. */
  title?: string;

  /** The description of the note, if available. */
  description?: string;

  /** The original URL associated with the note, if any. */
  url?: string;

  /** Tags associated with the note. */
  tags?: string[];

  /** The last updated timestamp of the parent note. */
  lastUpdatedAt?: number;
}

/**
 * Represents a chunk of a note's content.
 */
export interface NoteChunk {

  /**
   * The unique identifier for this chunk.
   * Format: `notechunk_<parentId>_<index>`
   */
  id: string;

  /** The ID of the original note from which this chunk was derived. */
  parentId: string;

  /** The text content of this specific chunk. */
  content: string;

  /** The number of characters in the original, clean content. */
  charCount: number;

  /**
   * An array of strings representing the hierarchy of Markdown headings
   * under which this chunk is located. Empty if not under any heading.
   * e.g., ["Main Topic", "Sub-section"]
   */
  headingPath?: string[];
  description?: string;

   /** Metadata specific to the chunk type, e.g., JSON path. */
  metadata?: {
    jsonPath?: string;
    section?: string; // For text segments within JSON strings
    [key: string]: any; // Allow other metadata
  };

  /** The original URL of the parent note, if available. */
  originalUrl?: string;

  /** The original tags of the parent note, if available. */
  originalTags?: string[];

  /** The title of the parent note, if available. */
  parentTitle?: string;

  /** The description of the parent note, if available. */
  parentDescription?: string;

  /** A contextual summary of the chunk, generated by an LLM to improve retrieval. */
  summary?: string;

  /** The type of the original document this chunk came from */
  originalType: 'note' | 'json' | 'text' | 'chat';

  /** The embedding vector for this chunk. */
  embedding?: number[];

  /** The `lastUpdatedAt` timestamp of the parent document at the time of chunking. */
  parentLastUpdatedAt?: number;
}

/**
 * Input type for chunking chat message content.
 */
export interface ChatMessageInputForChunking {

  /** The unique identifier of the original message. */
  id: string;

  /** The ID of the conversation this message belongs to. */
  conversationId: string;

  /** The main textual content of the message. */
  content: string;

  /** The role of the entity that produced the message. */
  role: 'user' | 'assistant' | 'tool';

  /** The timestamp of the message. */
  timestamp: number;

  /** The title of the parent conversation, if available. */
  parentTitle?: string;

  /** The last updated timestamp of the parent conversation. */
  lastUpdatedAt?: number;

  /** The last updated timestamp of the message itself. */
  messageLastUpdatedAt?: number;
}

/**
 * The result of chunking a chat message, containing both the chunks and a list of their IDs for indexing.
 */
export type GenericChunk = NoteChunk;

export interface ChunkingResult {
  chunks: NoteChunk[];
  summariesGenerated: number;
}
